name: anora
description: Make sense of your enterprise data leveraging powerful LLMs
version: 1.0.0+2
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_gen: any
  dio: ^5.4.3+1
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  redacted: ^1.0.11
  firebase_storage: ^11.7.5
  flutter_speed_dial: ^7.0.0
  uuid: ^4.4.0
  flutter_dotenv: ^5.1.0
  hive_flutter: ^1.1.0
  file_picker: ^8.0.3
  flutter_markdown: ^0.7.1
  vibration: ^1.8.4
  simple_ripple_animation: ^0.0.9
  auto_route: ^8.1.3
  flutter_native_splash: ^2.4.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0
  shadcn_ui: ^0.4.3
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^9.0.0
  #injectable: ^2.4.1
  heroicons: ^0.10.0
  speech_to_text_google_dialog: ^0.0.6
  speech_to_text: ^6.6.0
  avatar_view: ^1.0.1
  avatar_glow: ^3.0.1
  image_stack: ^2.1.1
  firebase_core: ^2.31.0
  form_validation: ^3.1.1
  form_validator: ^2.1.1
  path_provider: ^2.1.3
  hydrated_bloc: ^9.1.5


dependency_overrides:
  rive: ^0.13.4

  
dev_dependencies:
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.6
  build_runner: ^2.4.11
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  
  freezed: ^2.5.2
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/Google-Sans.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
flutter_launcher_icons:
  image_path: "assets/launcher_icon.png"
  android: true
  ios: true
flutter_assets:
  assets_path: assets/
  output_path: lib/src/app/
  filename: assets.dart

flutter_native_splash:
  color: "#020818"
  image: assets/launcher_icon.png
  color_dark: "#121212"
  image_dark: assets/launcher_icon.png

  web: false